import React, {useEffect, useState} from 'react';
import Header from "../../components/Header";
import Head from "next/head";
import {useRouter} from "next/router";
import ImageDetail from "../../components/imageComponents/ImageDetail";
import Link from "next/link";
import ImageService from "../../services/ImageService";
import image from "./index";
import ImageIndex from "./index";
import {console} from "next/dist/compiled/@edge-runtime/primitives/console";
import {current} from "@reduxjs/toolkit";



const ImageDetailPage = () => {
    const router = useRouter();
    const ImageId = router.query.imageId;

    const [order, setOrder] = useState(0);
    const initialImageState = {
        id:null,
        title:"",
        image:undefined,
        imageOrder:null
    }

    const [currentImage, setCurrentImage] = useState(initialImageState);
    const [nextImage, setNextImage] = useState(initialImageState);
    const [arrayState, setArrayState] = useState([]);
    const [size, setSize] = useState(0);


    useEffect(() => {

        if (ImageId==nextImage.imageOrder){
            setOrder(+ImageId)
            ImageService.get(+ImageId+1).then(
                res=>{
                    setCurrentImage(res.data)
                        //ternyata bisa masukin ke array bang
                    setArrayState(current=>[...current,res.data])
                    console.log(arrayState.length)
                }
            ).catch(e=>{
                console.log(e)
            })
        }else if (nextImage.imageOrder==null && currentImage.imageOrder != null) {
            setOrder(ImageId)
            ImageService.get(+ImageId).then(
                res=>{
                    setNextImage(res.data)
                    setCurrentImage(initialImageState)
                }
            ).catch(e=>{
                console.log(e)
            })
            setNextImage(initialImageState)
        } else {
            setOrder(ImageId)
            ImageService.get(+ImageId).then(
                res=>{
                    setCurrentImage(res.data)
                    setArrayState([...arrays,res.data])
                }
            ).catch(e=>{
                console.log(e)
            })
            ImageService.get(+ImageId+1).then(
                res=>{
                    setNextImage(res.data)
                }
            ).catch(e=>{
                console.log(e)
            })

        }


        ImageService.getSize().then(res => {
            setSize(res.data)
        }).catch(e=>{
            console.log(e)
        });
    }, [ImageId]);





    return (
        <div>
            <Head>
                <title>Belajar</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={"flex bg-gray-200"}>
                <div className={"bg-gray-200 flex-grow overflow-y-auto"}>
                    <div className="overflow-x-clip relative shadow-md  items-center">
                        <div className={"bg-gray-500 py-2 px-5 w-full grid justify-items-center text-white font-medium"}>
                            Page {order} of {size}
                        </div>
                        <div className={"grid justify-items-center"}>

                                <ImageDetail imageId={ImageId} nextImage={nextImage} currentImage={currentImage} />

                            <div className={"bg-gray-500 py-2 px-5 w-full grid justify-items-center text-white font-medium"}>



                                <div className={"flex"}>
                                    <Link href={`/image/`+(+order-1)} >Previous</Link>
                                    <div className={"px-2"}>
                                        Page {order} of {size}
                                    </div>
                                    <Link href={`/image/`+(+order+1)} >Next</Link>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </main>
        </div>
    );
};

export default ImageDetailPage;
