import React, {useEffect, useState} from 'react';
import Header from "../../components/Header";
import Head from "next/head";
import {useRouter} from "next/router";
import ImageDetail from "../../components/imageComponents/ImageDetail";
import Link from "next/link";
import ImageService from "../../services/ImageService";
import {console} from "next/dist/compiled/@edge-runtime/primitives/console";
import image from "./index";


const ImageDetailPage = () => {
    const router = useRouter();
    const {imageId} = router.query
    const [order, setOrder] = useState(0);
    const [arrayState, setArrayState] = useState([]);
    const [size, setSize] = useState(0);
    const [start, setStart] = useState(0);
    const [offSet, setOffSet] = useState(0);


    useEffect(() => {

        if(router.isReady){
            setOrder(imageId)


            ImageService.getSize().then(res => {
                setSize(res.data)
            }).catch(e=>{
                console.log(e)
            });

        }
        if(order==0){
            for (let i = +imageId; i <= +imageId+2; i++) {
                ImageService.get(i).then(
                    res=>{
                        setArrayState(current=>[...current,res.data])
                    }
                ).catch(e=>{
                    console.log(e)
                })

            }

            setStart(imageId)
            setOffSet(+imageId+3)
        }
       /* else if(+imageId+1==+offSet){
            console.log("triggered")
            for (let i = +imageId+2; i <= offSet+3; i++) {
                ImageService.get(i).then(
                    res=>{
                        setArrayState(current=>[...current,res.data])
                    }
                ).catch(e=>{
                    console.log(e)
                })

            }
            setStart(start+2)
            setOffSet(offSet+2)
        }*/


    }, [imageId, router.isReady]);

    //pusing mikirin beginian doang anying
    const previous = () =>{
        let found = false;
        for (let i = 0; i < arrayState.length; i++) {
            if(arrayState[i].imageOrder==(+imageId-1)){
                found = true;
                break;
            }
        }
        if(found){

        }else{
            ImageService.get(+imageId-1).then(
                res=>{
                    setArrayState(current=>[...current,res.data])
                }
            ).catch(e=>{
                console.log(e)
            })
        }

        router.push("/image/"+(+imageId-1))
    }

    const next = ()=>{

        if (offSet > size){

        }else {
            for (let i = offSet; i <= offSet+1; i++) {
                ImageService.get(i).then(
                    res=>{
                        setArrayState(current=>[...current,res.data])
                    }
                ).catch(e=>{
                    console.log(e)
                })
            }
            setOffSet(offSet+2)
        }

        if(+imageId == size){
            router.push("/image/")
            setArrayState([])
        }else {
            router.push("/image/"+(+imageId+1))
        }

    }


    return (
        <div>
            <Head>
                <title>Belajar</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={"flex bg-gray-200"}>
                <div className={"bg-gray-200 flex-grow overflow-y-auto"}>
                    <div className="overflow-x-clip relative shadow-md  items-center">
                        <div className={"bg-gray-500 py-2 px-5 w-full grid justify-items-center text-white font-medium"}>
                            Page {order} of {size}
                        </div>
                        <div className={"grid justify-items-center"}>

                                <ImageDetail props = {arrayState} imageId={imageId} />

                            <div className={"bg-gray-500 py-2 px-5 w-full grid justify-items-center text-white font-medium"}>


                                <div className={"flex"}>
                                    <button onClick={previous} >Previous</button>
                                    <div className={"px-2"}>
                                        Page {order} of {size}
                                    </div>
                                    <button onClick={next}>Next</button>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </main>
        </div>
    );
};

export default ImageDetailPage;
