import Head from 'next/head'
import Header from "../components/Header";
import Dashboard from "../components/Dashboard";
import {useDispatch, useSelector} from "react-redux";
import {useEffect} from "react";
import {getUserDetails} from "../public/src/features/UserSlice";

export default function Home() {

    const { userInfo, accessToken } = useSelector((state) => state.users)
    console.log(accessToken)
    const dispatch = useDispatch()
    useEffect(() => {
        if (accessToken) {
            dispatch(getUserDetails())
        }
    }, [accessToken, dispatch])

  return (
    <div>
      <Head>
        <title>Belajar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header userInfo={userInfo}/>
      <main className={"flex bg-gray-200"}>
         <Dashboard userInfo={userInfo} />
      </main>

      <footer >
      </footer>
    </div>
  )
}
