import React from 'react';
import Head from "next/head";
import Header from "../../components/Header";
import AwsUploadComponent from "../../components/awsUploadComponents/AwsUpload";

const AwsUpload = () => {
    return (
        <div>
            <Head>
                <title>Feature Demo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={"flex bg-gray-200"}>
                <AwsUploadComponent />
            </main>

            <footer >
            </footer>
        </div>
    );
};

export default AwsUpload;
